/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
  const ElCollection$1: typeof import('element-plus/es')['ElCollection$1']
  const ElCollectionItem$1: typeof import('element-plus/es')['ElCollectionItem$1']
  const ElMessage: typeof import('element-plus/es')['ElMessage']
  const ElMessageBox: typeof import('element-plus/es')['ElMessageBox']
}
