/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    AppSetting: typeof import('./src/components/AppSetting.vue')['default']
    ChatGPT: typeof import('./src/components/ChatGPT.vue')['default']
    ChatGPTBody: typeof import('./src/components/ChatGPTBody.vue')['default']
    ChatGPTBodyHeader: typeof import('./src/components/ChatGPTBodyHeader.vue')['default']
    ChatGPTBodyInput: typeof import('./src/components/ChatGPTBodyInput.vue')['default']
    ChatGPTBodyMessageList: typeof import('./src/components/ChatGPTBodyMessageList.vue')['default']
    ChatGPTBodySetting: typeof import('./src/components/ChatGPTBodySetting.vue')['default']
    ChatGPTMessageAssistant: typeof import('./src/components/ChatGPTMessageAssistant.vue')['default']
    ChatGPTMessageError: typeof import('./src/components/ChatGPTMessageError.vue')['default']
    ChatGPTMessageUser: typeof import('./src/components/ChatGPTMessageUser.vue')['default']
    ChatGPTSidebar: typeof import('./src/components/ChatGPTSidebar.vue')['default']
    ChatGPTSidebarHeader: typeof import('./src/components/ChatGPTSidebarHeader.vue')['default']
    ChatGPTSidebarSession: typeof import('./src/components/ChatGPTSidebarSession.vue')['default']
    ChatGPTSidebarSessionList: typeof import('./src/components/ChatGPTSidebarSessionList.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElOptionGroup: typeof import('element-plus/es')['ElOptionGroup']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
  }
}
